name: Set Environment vars
description: Set env vars from a file.

inputs:
  env_path:
    description: The path for the environment folder (without '/' in the end)
    required: false
    default: env
  context:
    required: false
    description: The context of the environment
    default: belender
  enable-pro:
    required: false
    description: Enable env PRO
    default: "true"
  enable-qa:
    required: false
    description: Enable env QA
    default: "true"
  enable-dev:
    required: false
    description: Enable env DEV
    default: "true"

runs:
  using: composite
  steps:
    - run: |
 
        echo "Context Name: ${{ inputs.context }}"
        echo "Ref Name: ${GITHUB_REF_NAME}"
        
        if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            export ENV=pro
        elif [[ "${GITHUB_REF_NAME}" == feature* ]]; then
            export ENV=dev
        elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            export ENV=dev
        elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
            export ENV=qa
        else
            echo "Error: Verifica el nombre de la rama"
            exit 1
        fi
        
        CONTEXT_PATH="${{ inputs.env_path }}/${{ inputs.context }}-${ENV}.env"
        
        if [ ! -f "${CONTEXT_PATH}" ]; then
          echo "El fichero de contexto: ${CONTEXT_PATH} no existe."
          exit 1
        fi
        
        echo "Env Selected: ${ENV}"
        echo "ENV=${ENV}" >> $GITHUB_ENV
        
        while IFS='=' read -r NAME VALUE; do
          if [[ -n "${NAME}" ]]; then
            echo "${NAME}=${VALUE}"
            echo "${NAME}=${VALUE}" >> $GITHUB_ENV
          fi
        done < ${CONTEXT_PATH}

      shell: bash